<a href="https://colab.research.google.com/github/jpitt2004/AI-Budget-Assistant/blob/main/Assignment_5_Airports_Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
tsaClaims = pd.read_csv("tsa_claims1-2.csv", low_memory=False)

In [ ]:
tsaClaims.head()

,Claim Number,Date Received,Incident Date,Airport Code,Airport Name,Airline Name,Claim Type,Claim Site,Item,Claim Amount,Status,Close Amount,Disposition
0,0909802M,4-Jan-02,12/12/2002 0:00,EWR,Newark International Airport,Continental Airlines,Property Damage,Checkpoint,Other,350.00,Approved,350.00,Approve in Full
1,0202445M,4-Feb-02,11/26/2003 0:00,STL,Lambert St. Louis International,American Airlines,Property Damage,Checked Baggage,Cell Phones,278.88,Settled,227.92,Settle
2,0909816M,7-Feb-02,1/6/2003 0:00,MIA,Miami International Airport,American Airlines,Property Damage,Checkpoint,Luggage (all types including footlockers),50.00,Approved,50.00,Approve in Full
3,2005032379513,18-Feb-02,2/5/2005 0:00,MCO,Orlando International Airport,Delta (Song),Property Damage,Checkpoint,Baby - Strollers; car seats; playpen; etc.,84.79,Approved,84.79,Approve in Full
4,2005032479636,18-Feb-02,2/17/2005 0:00,CAK,Akron-Canton Regional,Air Tran Airlines(do not use),Passenger Property Loss,Checked Baggage,Other,459.01,Settled,227.00,Settle

### **1. What is the most common type of insurance claim?**
---
**Answer:** The most common type of insurance claim is Passenger Property Loss, with 60,265 claims. See Below!

In [ ]:
# Question 1
tsaClaims['Claim Type'].value_counts()

Claim Type
Passenger Property Loss    60265
Property Damage            33730
Passenger Theft              331
Employee Loss (MPCECA)       308
Personal Injury              208
Motor Vehicle                  6
Name: count, dtype: int64

### **2. Which claim site within the airport are claims most commonly filed for?**
---
**Answer:** Claims are most commonly filed for Checked Baggage, with 80,553 claims. See Below!

In [ ]:
# Question 2
tsaClaims['Claim Site'].value_counts()

Claim Site
Checked Baggage    80553
Checkpoint         14013
Other                280
Motor Vehicle          2
Name: count, dtype: int64

### **3. What type of claim is made most at each claim site?**
---
**Answer:** Passenger Property Loss is the most common claim type for Checked Baggage, Motor Vehicle, and Other claim sites. Property Damage is the most common claim type at Checkpoints. See Below!

In [ ]:
# Question 3
tsaClaims.groupby('Claim Site')['Claim Type'].agg(
    lambda x: x.value_counts().index[0]
)

Claim Site
Checked Baggage    Passenger Property Loss
Checkpoint                 Property Damage
Motor Vehicle      Passenger Property Loss
Other              Passenger Property Loss
Name: Claim Type, dtype: object

### **4. What is the typical claim amount?**
---
**Answer:** The typical claim amount is about $183.69, based on the median. The median gives a better idea of a typical claim because there are some extremely high claim amounts that make the average much higher. See Below!

In [ ]:
# Question 4
pd.options.display.float_format = '{:.2f}'.format
tsaClaims['Claim Amount'].describe()

count       94848.00
mean         3634.83
std        524943.66
min             0.00
25%            65.00
50%           183.69
75%           480.64
max     125000000.00
Name: Claim Amount, dtype: float64

### **5. What is the overall claim approval rate for the entire U.S.?**
---
**Answer:** The overall claim approval rate for the United States is approximately 24.43%. See Below!

In [ ]:
# Question 5
approval_rate = (tsaClaims['Status'] == 'Approved').mean() * 100
approval_rate

np.float64(24.425396423751685)